#!/bin/bash
if [ $# -ne 2 ]; then
  echo "usage: $0 input_file.yaml output_file.json"
  echo "   eg: $0 contacts.yaml contacts.json"
  exit 1
fi
/usr/bin/env ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < $1 > $2
